
def call(Map logParams) {
    sh """
        echo  "发布文件名 : ${logParams.distFileName}"
        echo  "GIT_AUTHOR_NAME : ${params.GIT_AUTHOR_NAME}"
        echo  "BUILD_URL: ${env.BUILD_URL}"
        echo  "GIT_BRANCH: ${params.GIT_BRANCH}"
        echo  "CHANGE_ID: ${env.CHANGE_ID}"
        echo  "CHANGE_URL: ${env.CHANGE_URL}"
        echo  "CHANGE_TITLE: ${env.CHANGE_TITLE}"
        echo  "CHANGE_AUTHOR: ${env.CHANGE_AUTHOR}"
        echo  "CHANGE_AUTHOR_DISPLAY_NAME: ${env.CHANGE_AUTHOR_DISPLAY_NAME}"
        echo  "CHANGE_AUTHOR_EMAIL: ${env.CHANGE_AUTHOR_EMAIL}"
        echo  "CHANGE_TARGET: ${env.CHANGE_TARGET}"
        echo  "BUILD_ID: ${env.BUILD_ID}"
        echo  "BUILD_DISPLAY_NAME: ${env.BUILD_DISPLAY_NAME}"
        echo  "JOB_NAME: ${env.JOB_NAME}"
        echo  "JOB_BASE_NAME: ${env.JOB_BASE_NAME}"
        echo  "BUILD_TAG: ${env.BUILD_TAG}"
        echo  "NODE_NAME: ${env.NODE_NAME}"
        echo  "result: ${currentBuild.result}"
        echo  "displayName: ${currentBuild.displayName}"
        echo  "fullDisplayName: ${currentBuild.fullDisplayName}"
        echo  "timeInMillis: ${currentBuild.timeInMillis}"
        echo  "startTimeInMillis: ${currentBuild.startTimeInMillis}"
        echo  "durationString: ${currentBuild.durationString}"
        echo  "absoluteUrl: ${currentBuild.absoluteUrl}"
        echo  "description: ${currentBuild.description}"
      """
}